# Generated by Django 4.0.3 on 2022-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiceMasse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
